<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.202" />
    <PackageReference Include="TypeEquality" Version="0.3.0" />
    <PackageReference Include="WoofWare.Incremental" Version="0.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="PrivateEval\TypeId.fs" />
    <Compile Include="PrivateEval\TypeIdSet.fsi" />
    <Compile Include="PrivateEval\TypeIdSet.fs" />
    <Compile Include="PrivateEval\Trampoline.fsi" />
    <Compile Include="PrivateEval\Trampoline.fs" />
    <Compile Include="Vdom.fs" />
    <Compile Include="Bonsai.fs" />
  </ItemGroup>

</Project>